---
- name: Prepare the workstation
  hosts: localhost
  connection: local
  become: yes
  tasks:
    # INSTALL DNF APPS
    - name: Installing packages on Fedora
      block:
        - name: Loop for installation
          dnf:
            name: '{{ item }}'
            state: present
          loop:
            - curl
            - kitty
            - syncthing
            - vim
            - less
            - python-pip

    # INSTALL VISUAL STUDIO CODE
    - name: Install Visual Studio Code
      block:
        - name: Check if Visual Studio Code is installed
          stat:
            path: /usr/bin/code
          register: vscode_installed

        - name: Add Microsoft GPG key
          rpm_key:
            state: present
            key: https://packages.microsoft.com/keys/microsoft.asc
          when: not vscode_installed.stat.exists

        - name: Add Visual Studio Code repository
          copy:
            content: |
              [code]
              name=Visual Studio Code
              baseurl=https://packages.microsoft.com/yumrepos/vscode
              enabled=1
              gpgcheck=1
              gpgkey=https://packages.microsoft.com/keys/microsoft.asc
            dest: /etc/yum.repos.d/vscode.repo
            mode: '0644'
          when: not vscode_installed.stat.exists

        - name: Install Visual Studio Code
          dnf:
            name: code
            state: present
          when: not vscode_installed.stat.exists
