---
- name: Prepare the workstation
  hosts: localhost
  connection: local
  become: yes

  tasks:
    # INSTALL APT APPS
    - name: Update apt repository cache
      apt:
        update_cache: yes

    - name: Installing with apt
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - build-essential
        - curl
        - kitty
        - syncthing
        - vim
        - less
        - keepass2

    # INSTALL VISUAL STUDIO CODE
    - name: Install Visual Studio Code
      block:
        - name: Check if Visual Studio Code is installed
          stat:
            path: /usr/bin/code
          register: vscode_installed

        - name: Add Microsoft GPG key
          apt_key:
            url: https://packages.microsoft.com/keys/microsoft.asc
            state: present
          when: not vscode_installed.stat.exists

        - name: Add Visual Studio Code repository
          apt_repository:
            repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
            state: present
          when: not vscode_installed.stat.exists

        - name: Install Visual Studio Code
          apt:
            name: code
            state: present
          when: not vscode_installed.stat.exists
