---
- name: Prepare the workstation
  hosts: localhost
  connection: local

  tasks:
    # INSTALL APT APPS
    - name: Update apt repository cache
      apt:
        update_cache: yes
      become: true

    - name: Installing with apt
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - syncthing
        - vim
        - python-pip
        - python3
      become: true

    # config shell
    - name: Config bash
      block:
        - name: Set up theme
          lineinfile:
            path: ~/.bashrc
            regexp: '^OSH_THEME='
            line: 'OSH_THEME="absimple"'
            state: present

        - name: Set up dotfiles alias
          lineinfile:
            path: ~/.bashrc
            line: 'alias dotfiles="python3 ~/.dotfiles/bin/main.py"'
            create: yes
                      
        - name: Set up nvm
          lineinfile:
            path: ~/.bashrc
            line: 'export NVM_DIR="$HOME/.nvm"'
            create: yes

        - name: Load up nvm
          lineinfile:
            path: ~/.bashrc
            line: '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"'
            create: yes

        - name: Set up sdkman!
          lineinfile:
            path: ~/.bashrc
            line: 'export SDKMAN_DIR="$HOME/.sdkman"'
            create: yes

        - name: Load sdkman!
          lineinfile:
            path: ~/.bashrc
            line: '[[ -s "$SDKMAN_DIR/bin/sdkman-init.sh" ]] && source "$SDKMAN_DIR/bin/sdkman-init.sh"'
            create: yes